### ISSUE TITLE
General questions related to the method

### ISSUE THREAD

**Issue by s-t-calus** [MustoeLab/DanceMapper#6]
Hello @Psirving and @anthonymustoe 

What is the reason to use DMS chemical instead of SHAPE based on NAI or 5NIA? I know that dimethyl sulfate has got significantly higher reactivity profile in cells but the most recently described 2A3 probe outperforms NAI or NAI-N3. Did you also consider or tested this newest 2A3 chemical with DANCE-MaP algorithm? Moreover, I've noticed that DREEM and DRACO algorithms are all based on DMS-MaP data, what is the reason for that and shall I stop using NAI/2A3 and move to DMS only?

I did not find any benchmarking of your DANCE algorithm against DREEM or DRACO packages, was that performed internally and is there any significant difference in final results between these three programs? 

Thank you very much for your help!
s-t-calus

**Comment by anthonymustoe** [comment]
Hello, 

DMS is used because of its ability to achieve high modification rates. We have not tested using 2A3 or other SHAPE reagents. It may work, but will require rigorous validation. Note that in addition to overall modification, there are also important differences in chemistry (reaction at base pairing face versus 2'OH, time of reaction, etc) that may also be consequential. 

All algorithms have been benchmarked on the adenine riboswitch. These data are published within each of the papers. For this RNA, all algorithms give generally similar results, although there are subtle but meaningful differences in reactivity profiles and populations. It is challenging to do a more comprehensive benchmark because of a paucity of independently validated "known" datasets. We found DREEM yields similar (although again subtly different) results for 7SK. We had trouble building DRACO and thus have not tested this algorithm.
